### ISSUE TITLE
[Bug] Commands not all working

### ISSUE THREAD

**Issue by MysticAura** [MattDahEpic/MDECore1.8#8]
MC: 1.10.2
Forge: 2086
Mod Version: mdecore-1.10.2-1.1

/mde regen doesn't exist, which is kind of a shame since it was one of the main reasons I added it to the pack to help with server maintenance.

Many other commands throw an error instead of running (The typical 'An unknown error occured...') mde tps was one of these.

**Comment by MattDahEpic** [comment]
Could I get the logs which have the errors that are thrown?

/mde regen stopped working in 1.9 and I have yet to find a way to make it work, but I'm still looking.

**Comment by SmallSansSerif** [comment]
[11:41:38] [Server thread/WARN]: Couldn't process command: 'mde pregen'
java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
        at com.mattdahepic.mdecore.command.logic.PregenLogic.getCommandSyntax(PregenLogic.java:32) ~[mdecore-1.10.2-1.1.jar:?]
        at com.mattdahepic.mdecore.command.AbstractCommand.throwUsages(AbstractCommand.java:93) ~[mdecore-1.10.2-1.1.jar:?]
        at com.mattdahepic.mdecore.command.logic.PregenLogic.handleCommand(PregenLogic.java:37) ~[mdecore-1.10.2-1.1.jar:?]
        at com.mattdahepic.mdecore.command.AbstractCommand.func_184881_a(AbstractCommand.java:70) ~[mdecore-1.10.2-1.1.jar:?]
        at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:104) [k.class:?]
        at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:83) [k.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:913) [me.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:892) [me.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [im.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [im.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.resources.I18n
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_45]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_45]
        ... 19 more
Caused by: java.lang.NullPointerException
